### ISSUE TITLE
How do I change colors for accents ?

### ISSUE THREAD

**Issue by pavanpodila** [HiDeoo/starlight-theme-rapide#12]
### Describe the bug

I love the theme and would like to change the accent color ? Is there an easy way to set the variable or update some config ? I could not find a direct way to do this.

### To Reproduce

No easy way to change accent color

### Expected behavior

There should be some config to change colors

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
Thanks for the feedback :raised_hands: 

At the moment, customization can be done by using Starlight [custom CSS](https://starlight.astro.build/guides/css-and-tailwind/#custom-css-styles) and overriding some CSS variables or classes. In the case of the accent colors, the 3 main variables would be `--sl-color-accent-low`, `--sl-color-accent`, and `--sl-color-accent-high` (you can find a complete list [here](https://github.com/HiDeoo/starlight-theme-rapide/blob/main/packages/starlight-theme-rapide/styles.css)).

Altho, until Cascade Layers are supported by Starlight (currently [WIP](https://github.com/withastro/starlight/pull/2322)), you may need to trick the specificity of the CSS selectors to override the default values set by the theme. For example, you can use `:root:is(:root)` instead of `:root` to increase the specificity of the selector.

```css
:root:is(:root),
::backdrop:is(::backdrop) {
  --sl-color-accent-low: red;
  --sl-color-accent: red;
  --sl-color-accent-high: red;
}
```

The above CSS will override the accent colors to red:

<img width="1347" alt="image" src="https://github.com/user-attachments/assets/4f7604fd-d0be-4068-88f2-70add121b17c">

**Comment by lmnzx** [comment]
which this config i could change the color for all the elements except the codebloacks,
```css
:root:is(:root),
::backdrop:is(::backdrop) {
	--sl-color-accent-low: #251d3e;
	--sl-color-accent: #704dc7;
	--sl-color-accent-high: #c9c2ee;
	--sl-color-white: #ffffff;
	--sl-color-gray-1: #ececfb;
	--sl-color-gray-2: #c0c0d2;
	--sl-color-gray-3: #8888a9;
	--sl-color-gray-4: #555473;
	--sl-color-gray-5: #353451;
	--sl-color-gray-6: #24233e;
	--sl-color-black: #171723;
}

:root[data-theme='light']:is(:root[data-theme='light']),
[data-theme='light'] ::backdrop:is(::backdrop) {
    --sl-color-accent-low: #d7d2f3;
    --sl-color-accent: #714fca;
    --sl-color-accent-high: #34275c;
    --sl-color-white: #171723;
    --sl-color-gray-1: #24233e;
    --sl-color-gray-2: #353451;
    --sl-color-gray-3: #555473;
    --sl-color-gray-4: #8888a9;
    --sl-color-gray-5: #c0c0d2;
    --sl-color-gray-6: #ececfb;
    --sl-color-black: #ffffff;
}
```

How to change the colors of the codeblocks? what variables to modify?
