### ISSUE TITLE
Banner displaced on larger screes

### ISSUE THREAD

**Issue by trueberryless** [HiDeoo/starlight-theme-rapide#26]
### Describe the bug

The banner is displaced on larger screens like that:

![Image](https://github.com/user-attachments/assets/81ce7f7e-5255-46d8-8bf3-eb7ea5948962)

This is very likely a regression issue of commit https://github.com/HiDeoo/starlight-theme-rapide/pull/23/commits/a91b466196f2dd48f884e32aa5ddb1ede26009ad#diff-f4b1f7f3ea5346419e665bd30edf59ee3d2c9a8abe54afd91b71c1a2f7606b0d

This is partly my fault because I was unable to finish [the initial suggestion PR](https://github.com/HiDeoo/starlight-theme-rapide/pull/22). I'm not sure what the optimal CSS-only solution would be in this case.

If it helps, here is some cheesy CSS from my NextJS theme: 

```css
.sl-banner {
  background-color: var(--sl-color-accent-low);
  border: 1px solid var(--sl-color-accent-high);
  border-radius: 0.5rem;
  color: var(--sl-color-white);
  line-height: 1.4;
  margin: 2rem var(--sl-content-pad-x);
  padding: 1rem;
  text-align: start;
  text-wrap: wrap;
}

@media (min-width: 1400px) {
  html[data-has-sidebar] .sl-banner {
    width: var(--sl-content-width);
    float: right;
  }
}

html:not([data-has-sidebar]) .sl-banner {
  margin-inline: var(--sl-nav-pad-x);
}

.sl-banner a {
  color: var(--sl-color-accent-high);
  text-underline-offset: 0.25em;
}
```

### To Reproduce

1. Go to https://starlight-theme-rapide.vercel.app/examples/banner/

### Expected behavior

The Banner should be centralized like the Markdown content.

### How often does this bug happen?

Every time

**Comment by trueberryless** [comment]
Now I remember what the problem with my CSS is:

There is a small range of screen widths where the banner is too long on the right side, like you can see here:

![Image](https://github.com/user-attachments/assets/8048dfc9-600c-402e-a496-94c1a6a521f2)

So to sum up, neither my nor your CSS is perfect, they currently just have different problems 😆 
I'll see if I can figure out better CSS which fixes all of this. If I'm able to, I'll suggest it here...

**Comment by trueberryless** [comment]
Okay, adding something like this:

```css

  @media (min-width: 88.5rem) {
    [data-has-sidebar] & {
      margin-left: auto;
      margin-right: var(--sl-content-pad-x);
    }
  }
```

seems to do the trick.

Alto I question myself, where these `88.5rem` come from? The highest `@media (min-width...)` in Starlight is `72rem`.
I think the answer to this question is because the main content and the ToC get `display: flex`ed so it is just "pure coincidence" or call it "trail and error". But 88.5rem == 1416px on my PC and I tested it with this CSS on all whole values from 1400px to 1430px and it looks good. Some random "sub-pixel" offsets happen however, which I'll try to show here:

Look closely to the start of the banner compared to the heading "Banner". It kinda "jumps" little bit left and right.

https://github.com/user-attachments/assets/d11cc1ac-3455-4067-9888-911a5d8606b4

But imo this small "weirdness" is okay to include, so I'm gonna create a PR if it's okay for you
